package com.allegianttravel.ota.flight.shop.qpx;

import com.allegiant.util.property.PropertySetEnum;

import javax.annotation.Generated;

public enum QpxProperties implements PropertySetEnum {

    APPLICATION_NAME("ota-flight3-shop-provider.qpx.application-name", "provider-qpx"),
    API_KEY("ota-flight3-shop-provider.qpx.api-key", "AIzaSyALMjtuYEEI5mNnLPmDIOtgVQpCAVcPcdg")
            ;

    private final String key;
    private final String valueDefault;

    QpxProperties(String key, String valueDefault) {
        this.key = key;
        this.valueDefault = valueDefault;
    }

    @Override
    @Generated("Generated by IDE")
    public String getKey() {
        return key;
    }

    @Override
    @Generated("Generated by IDE")
    public String getValueDefault() {
        return valueDefault;
    }
}
