/*
 *
 *  * Copyright (C) 2017 Allegiant Travel Company - All Rights Reserved
 *  *
 *  * This file is subject to the terms and conditions defined in
 *  * file 'LICENSE.txt', which is part of this source code package.
 *
 *
 */

package com.allegianttravel.ota.flight.shop.provider;

import javax.annotation.Generated;

public class CallerMetadata {
    private final String apiKey;
    private final String callerKey;
    private final String sessionKey;
    private final String callKey;

    CallerMetadata(Builder builder) {
        this.apiKey = builder.getApiKey();
        this.callerKey = builder.getCallerKey();
        this.sessionKey = builder.getSessionKey();
        this.callKey = builder.getCallKey();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String apiKey;
        private String callerKey;
        private String sessionKey;
        private String callKey;

        public CallerMetadata build() {
            return new CallerMetadata(this);
        }

        @Generated("Generated by IDE")
        public String getApiKey() {
            return apiKey;
        }

        @Generated("Generated by IDE")
        public Builder setApiKey(String apiKey) {
            this.apiKey = apiKey;
            return this;
        }

        @Generated("Generated by IDE")
        public String getCallerKey() {
            return callerKey;
        }

        @Generated("Generated by IDE")
        public Builder setCallerKey(String callerKey) {
            this.callerKey = callerKey;
            return this;
        }

        @Generated("Generated by IDE")
        public String getSessionKey() {
            return sessionKey;
        }

        @Generated("Generated by IDE")
        public Builder setSessionKey(String sessionKey) {
            this.sessionKey = sessionKey;
            return this;
        }

        @Generated("Generated by IDE")
        public String getCallKey() {
            return callKey;
        }

        @Generated("Generated by IDE")
        public Builder setCallKey(String callKey) {
            this.callKey = callKey;
            return this;
        }
    }

    @Generated("Generated by IDE")
    public String getApiKey() {
        return apiKey;
    }

    @Generated("Generated by IDE")
    public String getCallerKey() {
        return callerKey;
    }

    @Generated("Generated by IDE")
    public String getSessionKey() {
        return sessionKey;
    }

    @Generated("Generated by IDE")
    public String getCallKey() {
        return callKey;
    }

    @Override
    @Generated("by IDE")
    public String toString() {
        return "CallerMetadata{" +
                "apiKey='" + apiKey + '\'' +
                ", callerKey='" + callerKey + '\'' +
                ", sessionKey='" + sessionKey + '\'' +
                ", callKey='" + callKey + '\'' +
                '}';
    }
}
