@startuml

object "SegmentDto" as segmentdto
object "FareDto" as fareClub
object "Tax" as fcTax
object "Fee" as fcFeePfc
object "Fee" as fcFeeSegment
object "Fee" as fcFeeSecurity
object "ShopDto" as shopdto

object "RatePlan" as new #LightBlue
object "RatePlan" as cbp #LightBlue
object "RatePlan" as agt #Orange

object "DiscountReason" as roundTripDiscount
object "DiscountReason" as fareClubDiscount

object new {
    code = NEW
    oneway = 50.98
    roundtrip = 40.98
}

object cbp {
    code = CBP
    oneway = 10.05
    roundtrip = 10.05
}

object agt {
    code = AGT
    oneway = 30.05
    roundtrip = 30.05
}

object shopdto {

}

object segmentdto {

}

object fareClub {
    fareClass = "L"
    ratePlanCode = "LCBP"
    baseFare = $10.05
    couponCode = CBP
    strikethruBaseFare = $50.98
    +salesTotal = $25.00
    +strikethruSalesTotal = $69.00
}

object fcTax {
    name = Excise Tax
    code = XT
    rate = 0.075
}

object fcFeePfc {
    name = Passenger Facility Charge
    code = PFC
    amount = $4.50
}

object fcFeeSegment {
    name = Segment Fees
    code = ZP
    amount = $4.10
}

object fcFeeSecurity {
    name = Security Fee
    code = SEC
    amount = $5.60
}

object roundTripDiscount {
    name = ROUNDTRIP
    amount = 10.00
            <b>(50.98 - 40.98)</b>
}

object fareClubDiscount {
    name = COUPON
    amount = 30.93
            <b>(40.98 - 10.05)</b>
}

shopdto *-- segmentdto

shopdto *-- fareClub


fareClub *-- fcFeeSecurity
fareClub *-- fcFeeSegment
fareClub *-- fcFeePfc
fareClub *-- fcTax

fareClub *-- roundTripDiscount
fareClub *-- fareClubDiscount

@enduml